from django.db import models
from .angariadores import *

class Clientes(models.Model):
    cpf = models.CharField(max_length=50, unique=True, verbose_name='CPF')
    matricula = models.CharField(max_length=50, unique=True)
    nome = models.CharField(max_length=255)
    logradouro = models.CharField(max_length=255, blank=True, null=True)
    numero = models.CharField(max_length=50, blank=True, null=True)
    complemento = models.CharField(max_length=255, blank=True, null=True)
    bairro = models.CharField(max_length=255, blank=True, null=True)
    cidade = models.CharField(max_length=255, blank=True, null=True)
    uf = models.CharField(max_length=2, blank=True, null=True)
    segundoendereco = models.CharField(max_length=255, blank=True, null=True)
    cep = models.CharField(max_length=30, blank=True, null=True)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    ramal = models.CharField(max_length=10, blank=True, null=True)
    fax = models.CharField(max_length=20, blank=True, null=True)
    ramalfax = models.CharField(max_length=10, blank=True, null=True)
    celulares = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, blank=True, null=True)
    banco = models.CharField(max_length=50, blank=True, null=True)
    agencia = models.CharField(max_length=20, blank=True, null=True)
    cc = models.CharField(max_length=50, blank=True, null=True)
    nascimento = models.DateField(blank=True, null=True)
    identidade = models.CharField(max_length=50, blank=True, null=True)
    orgao = models.CharField(max_length=50, blank=True, null=True)
    expedicao = models.DateField(blank=True, null=True)
    estadocivil = models.CharField(max_length=20, blank=True, null=True)
    sexo = models.CharField(max_length=10, choices=[('M', 'Masculino'), ('F', 'Feminino')], blank=True, null=True)
    rota = models.CharField(max_length=50, blank=True, null=True)
    localizador = models.CharField(max_length=50, blank=True, null=True)
    cargo = models.CharField(max_length=100, blank=True, null=True)
    funcao = models.CharField(max_length=100, blank=True, null=True)
    salario = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    codunid = models.CharField(max_length=50, blank=True, null=True)
    angariador = models.ForeignKey(Angariadores, on_delete=models.PROTECT, null=True, blank=True)
    dco = models.CharField(max_length=50, blank=True, null=True)
    codconv = models.CharField(max_length=50, blank=True, null=True)
    subconv = models.CharField(max_length=50, blank=True, null=True)
    codclube = models.CharField(max_length=50, blank=True, null=True)
    codaverba = models.CharField(max_length=50, blank=True, null=True)
    conjuge = models.CharField(max_length=255, blank=True, null=True)
    nascimentoconjuge = models.DateField(blank=True, null=True)
    cpfconjuge = models.CharField(max_length=50, blank=True, null=True)
    sexoconjuge = models.CharField(max_length=10, choices=[('M', 'Masculino'), ('F', 'Feminino')], blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True)
    empresa = models.CharField(max_length=100, blank=True, null=True)
    anuencia = models.CharField(max_length=50, blank=True, null=True)
    correspondencia = models.CharField(max_length=255, blank=True, null=True)
    dataanuencia = models.DateField(blank=True, null=True)
    controle = models.CharField(max_length=30, blank=True, null=True)
    certificado = models.CharField(max_length=50, blank=True, null=True)
    angariadoranuencia = models.CharField(max_length=50, blank=True, null=True)
    caminho = models.CharField(max_length=255, blank=True, null=True)
    mat_antiga = models.CharField(max_length=50, blank=True, null=True)
    control_antigo = models.CharField(max_length=50, blank=True, null=True)
    codclube_antigo = models.CharField(max_length=50, blank=True, null=True)
    Anuencia_Antiga = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return f"{self.nome}"
    
    

    