# Generated by Django 5.2.5 on 2025-08-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='codangariador',
        ),
        migrations.AddField(
            model_name='clientes',
            name='angariador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.angariadores'),
        ),
        migrations.CreateModel(
            name='BeneficiariosNovos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('nascimento', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=30, null=True)),
                ('percentual', models.FloatField(blank=True, null=True)),
                ('controle', models.CharField(blank=True, max_length=10, null=True)),
                ('apolice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.apolicebase')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.clientes')),
            ],
        ),
        migrations.DeleteModel(
            name='Beneficiarios',
        ),
    ]
