# Generated by Django 5.2 on 2025-05-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf',
            field=models.CharField(max_length=50, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpfconjuge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
