# Generated by Django 5.2.5 on 2025-08-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_clientes_codangariador_clientes_angariador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agregados',
            name='controle',
        ),
        migrations.RemoveField(
            model_name='agregados',
            name='marcador',
        ),
    ]
