# Generated by Django 5.2 on 2025-05-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_clientes_cpf_alter_clientes_cpfconjuge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='controle',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='idadeconj',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='isant',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='isconjant',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='nascimentoconj',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='premioant',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='premioconjant',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='controle',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='custoacessorio',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='idadeconj',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='insconjant',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='isant',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='nascimentoconj',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='penultimoreajuste',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='premioant',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='premioanterior',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='premioconjant',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='premioconjugeanterior',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='premiototal',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='ultimoreajuste',
        ),
    ]
