# Generated by Django 5.2.5 on 2025-08-18 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_agregados_controle_remove_agregados_marcador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agregados',
            name='angariador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.angariadores'),
        ),
    ]
