# Generated by Django 5.2 on 2025-05-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_apolicescifptd_controle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='apolicescifptd',
            name='alteradoconj',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='isant',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='penultimoreajuste',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='premioant',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='premioanterior',
        ),
        migrations.RemoveField(
            model_name='apolicese',
            name='ultimoreajuste',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='custoacessorio',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='isant',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='penultimoreajuste',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='premioant',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='premioanterior',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='premiototal',
        ),
        migrations.RemoveField(
            model_name='apolicesm',
            name='ultimoreajuste',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='alteradoconj',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='isant',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='nascimento',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='premioanterior',
        ),
        migrations.RemoveField(
            model_name='decesso',
            name='premioatn',
        ),
    ]
