# Generated by Django 5.2 on 2025-05-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_apolicescifptd_alterado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
