# Generated by Django 5.2.5 on 2025-08-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agregados_angariador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolicescarro',
            name='dataCancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicescarro',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicescarro',
            name='versao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesmoto',
            name='dataCancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesmoto',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesmoto',
            name='versao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesresidencia',
            name='dataCancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesresidencia',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesresidencia',
            name='versao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesvida',
            name='dataCancelamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesvida',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicesvida',
            name='referencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
