# Generated by Django 5.2 on 2025-05-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientes_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apolicessifptd',
            name='certificado',
        ),
    ]
