# Generated by Django 5.2.5 on 2025-08-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_apolicescarro_datacancelamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apolicesgerais',
            name='seguradora',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
