# Generated by Django 5.2 on 2025-05-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_apolicessifptd_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apolicessifptd',
            name='anuencia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apolicessifptd',
            name='anuenciaconjuge',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
