# Generated by Django 5.2 on 2025-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_apolicessifptd_anuencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apolicesm',
            name='cpfm',
        ),
    ]
