# Generated by Django 5.2.5 on 2025-08-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicalagregados_historicalangariadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsinistros',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Comunicado'), ('P', 'Pago'), ('R', 'Recusado')], default='C', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='sinistros',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Comunicado'), ('P', 'Pago'), ('R', 'Recusado')], default='C', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalsinistros',
            name='titular',
            field=models.CharField(blank=True, choices=[('T', 'Titular'), ('C', 'Conjuge'), ('O', 'Outro')], default='T', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sinistros',
            name='titular',
            field=models.CharField(blank=True, choices=[('T', 'Titular'), ('C', 'Conjuge'), ('O', 'Outro')], default='T', max_length=1, null=True),
        ),
    ]
