# Generated by Django 5.2 on 2025-05-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_apolicesm_cpfm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apolicesm',
            name='idade',
        ),
    ]
