# Generated by Django 5.2.5 on 2025-08-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_historicalsinistros_status_sinistros_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsinistros',
            name='titular',
            field=models.CharField(blank=True, choices=[('T', 'Titular'), ('C', 'Conjuge'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sinistros',
            name='titular',
            field=models.CharField(blank=True, choices=[('T', 'Titular'), ('C', 'Conjuge'), ('O', 'Outro')], max_length=1, null=True),
        ),
    ]
